### PR TITLE
[HOLD] chore(dockerfile): move to python 3.8

### PR DESCRIPTION
**Pull request by georgettica**
this is good as there are no vounrabilities there

### CODE REVIEW

**Comment by georgettica** [comment]
nah, doesn't matter really

**Comment by lmilbaum** [comment]
Is it a draft PR or do you want us to review?

**Comment by georgettica** [comment]
Not much to review, will explain on it on Sunday

**Comment by lmilbaum** [comment]
Again, is it a draft PR? If not, what is the meaning of the 'HOLD'? 
reviewer list is empty.

**Comment by georgettica** [comment]
It's here because I thought this would solve an issue I saw.

It didn't so we need to prioritize and do it when it's more relevant

**Comment by lmilbaum** [comment]
Then please close it

**Comment by georgettica** [comment]
As you wish

**Pull request closed without merging**
