### PR TITLE
refactor(deploy): change folder name

### PR DESCRIPTION
**Pull request by georgettica**

### CODE REVIEW

**Review by lmilbaum — APPROVED** [review]
gitignore file should be tracked in the project root folder. One per project.

**Comment by lmilbaum** [comment]
BTW, do we want to invoke the playbook in the CI?

**Comment by georgettica** [comment]
we might, didn't think of it @lioramilbaum.
will delete the gitignore  / move it to the root

**Review by lmilbaum — APPROVED** [review]
LGTM

**Pull request merged**
